export const CARDS_ADD_CARD = 'CARDS_ADD_CARD';
export const CARDS_EDIT_CARD = 'CARDS_EDIT_CARD';
export const LIST_REORDER_CARD = 'LIST_REORDER_CARD';

export const LANE_ADD_CARD = 'LANE_ADD_CARD';
export const LANE_REORDER_CARDS = 'LANE_REORDER_CARDS';
export const LANE_REORDER_CARDS_BETWEEN_LANES = 'LANE_REORDER_CARDS_BETWEEN_LANES';

export const BOARD_ADD_LANE = 'BOARD_ADD_LANE';
export const BOARD_EDIT_LANE = 'BOARD_EDIT_LANE';