export const LIST_ADD_TODO = 'LIST_ADD_TODO';
export const LIST_EDIT_TODO = 'LIST_EDIT_TODO';
export const LIST_REORDER_TODO = 'LIST_REORDER_TODO';

export const BOARD_ADD_LANE = 'BOARD_ADD_LANE';
export const BOARD_EDIT_LANE = 'BOARD_EDIT_LANE';